let dummyData = [
  {
    id: "1",
    first_name: "Lonnie",
    last_name: "O' Connell",
    gender: "Male",
    time: "7/10/2022",
    status: "true",
  },
  {
    id: "2",
    first_name: "Nikolos",
    last_name: "Botler",
    gender: "Male",
    time: "12/25/2021",
    status: "false",
  },
  {
    id: "3",
    first_name: "Burgess",
    last_name: "Caddens",
    gender: "Male",
    time: "2/24/2022",
    status: "false",
  },
  {
    id: "4",
    first_name: "Elissa",
    last_name: "Lesslie",
    gender: "Female",
    time: "3/13/2022",
    status: "false",
  },
  {
    id: "5",
    first_name: "Donaugh",
    last_name: "Nusche",
    gender: "Male",
    time: "6/2/2022",
    status: "true",
  },
  {
    id: "6",
    first_name: "Guillaume",
    last_name: "Edgcumbe",
    gender: "Male",
    time: "11/24/2022",
    status: "true",
  },
  {
    id: "7",
    first_name: "Berti",
    last_name: "Coldbath",
    gender: "Male",
    time: "6/8/2022",
    status: "true",
  },
  {
    id: "8",
    first_name: "Daune",
    last_name: "Brumen",
    gender: "Female",
    time: "8/17/2022",
    status: "false",
  },
  {
    id: "9",
    first_name: "Aigneis",
    last_name: "De Ruel",
    gender: "Female",
    time: "8/31/2022",
    status: "false",
  },
  {
    id: "10",
    first_name: "Khalil",
    last_name: "McQuorkel",
    gender: "Male",
    time: "10/25/2022",
    status: "false",
  },
];

export default dummyData;
